/* tslint:disable */
/* eslint-disable */
/**
 * Conduit API
 * Conduit API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Article } from './article';
/**
 * 
 * @export
 * @interface MultipleArticlesResponse
 */
export interface MultipleArticlesResponse {
    /**
     * 
     * @type {Array<Article>}
     * @memberof MultipleArticlesResponse
     */
    articles: Array<Article>;
    /**
     * 
     * @type {number}
     * @memberof MultipleArticlesResponse
     */
    articlesCount: number;
}
