/* tslint:disable */
/* eslint-disable */
/**
 * Conduit API
 * Conduit API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface NewArticle
 */
export interface NewArticle {
    /**
     * 
     * @type {string}
     * @memberof NewArticle
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof NewArticle
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof NewArticle
     */
    body: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof NewArticle
     */
    tagList?: Array<string>;
}
