/* tslint:disable */
/* eslint-disable */
/**
 * Conduit API
 * Conduit API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NewArticle } from './new-article';
/**
 * 
 * @export
 * @interface NewArticleRequest
 */
export interface NewArticleRequest {
    /**
     * 
     * @type {NewArticle}
     * @memberof NewArticleRequest
     */
    article: NewArticle;
}
